import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const galleries = [
    {
        user_id: 1,
        category_service_id: 1,
        gallery_type: "image",
        occasion_type: 1,
        gallery_image: "storage/uploads/gallery/sample-1.jpg",
        gallery_video: null,
        status: 1,
        created_by: 1,
        updated_by: 0,
    },
    {
        user_id: 1,
        category_service_id: 1,
        gallery_type: "image",
        occasion_type: 1,
        gallery_image: "storage/uploads/gallery/sample-2.jpg",
        gallery_video: null,
        status: 1,
        created_by: 1,
        updated_by: 0,
    },
    {
        user_id: 1,
        category_service_id: 1,
        gallery_type: "image",
        occasion_type: 2,
        gallery_image: "storage/uploads/gallery/sample-3.jpg",
        gallery_video: null,
        status: 1,
        created_by: 1,
        updated_by: 0,
    },
    {
        user_id: 1,
        category_service_id: 1,
        gallery_type: "image",
        occasion_type: 3,
        gallery_image: "storage/uploads/gallery/sample-4.jpg",
        gallery_video: null,
        status: 1,
        created_by: 1,
        updated_by: 0,
    },
    {
        user_id: 2,
        category_service_id: 2,
        gallery_type: "image",
        occasion_type: 1,
        gallery_image: "storage/uploads/gallery/sample-5.jpg",
        gallery_video: null,
        status: 1,
        created_by: 2,
        updated_by: 0,
    },
    {
        user_id: 2,
        category_service_id: 2,
        gallery_type: "image",
        occasion_type: 2,
        gallery_image: "storage/uploads/gallery/sample-1.jpg",
        gallery_video: null,
        status: 1,
        created_by: 2,
        updated_by: 0,
    },
    {
        user_id: 2,
        category_service_id: 2,
        gallery_type: "image",
        occasion_type: 4,
        gallery_image: "storage/uploads/gallery/sample-2.jpg",
        gallery_video: null,
        status: 1,
        created_by: 2,
        updated_by: 0,
    },
    {
        user_id: 3,
        category_service_id: 3,
        gallery_type: "video",
        occasion_type: 1,
        gallery_image: null,
        gallery_video: "storage/uploads/gallery/sample-3.mp4",
        status: 1,
        created_by: 3,
        updated_by: 0,
    },
    {
        user_id: 3,
        category_service_id: 3,
        gallery_type: "video",
        occasion_type: 2,
        gallery_image: null,
        gallery_video: "storage/uploads/gallery/sample-4.mp4",
        status: 1,
        created_by: 3,
        updated_by: 0,
    },
    {
        user_id: 3,
        category_service_id: 3,
        gallery_type: "image",
        occasion_type: 5,
        gallery_image: "storage/uploads/gallery/sample-5.jpg",
        gallery_video: null,
        status: 1,
        created_by: 3,
        updated_by: 0,
    },
    {
        user_id: 4,
        category_service_id: 4,
        gallery_type: "image",
        occasion_type: 6,
        gallery_image: "storage/uploads/gallery/sample-1.jpg",
        gallery_video: null,
        status: 1,
        created_by: 4,
        updated_by: 0,
    },
    {
        user_id: 4,
        category_service_id: 4,
        gallery_type: "image",
        occasion_type: 1,
        gallery_image: "storage/uploads/gallery/sample-2.jpg",
        gallery_video: null,
        status: 1,
        created_by: 4,
        updated_by: 0,
    },
    {
        user_id: 4,
        category_service_id: 4,
        gallery_type: "video",
        occasion_type: 1,
        gallery_image: null,
        gallery_video: "storage/uploads/gallery/sample-3.mp4",
        status: 1,
        created_by: 4,
        updated_by: 0,
    },
    {
        user_id: 5,
        category_service_id: 5,
        gallery_type: "image",
        occasion_type: 1,
        gallery_image: "storage/uploads/gallery/sample-4.jpg",
        gallery_video: null,
        status: 1,
        created_by: 5,
        updated_by: 0,
    },
    {
        user_id: 5,
        category_service_id: 5,
        gallery_type: "image",
        occasion_type: 3,
        gallery_image: "storage/uploads/gallery/sample-5.jpg",
        gallery_video: null,
        status: 1,
        created_by: 5,
        updated_by: 0,
    },
];

async function gallerySeeder(prisma) {
    await prisma.gallery.createMany({
        data: galleries,
        skipDuplicates: true,
    });

    console.log("Galleries seeded successfully.");
}

export default gallerySeeder;

